name: Node.js CI and Docker Build Reusable

on:
  workflow_call:
    secrets:
        REGISTRY_USERNAME:
          required: true
        REGISTRY_PASSWORD:
          required: true

jobs:

  node-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
      env:
        NPM_AUTH_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
    - run: npm run build --if-present
    # - run: npm test
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest
    - name: docker push
      run: |
        docker push ghcr.io/${{ github.repository }}:latest
